package j051_Encapsulation;

public class Employee 
{
	private String name;  //Set variable as private
	private int salary;  //Set variable as private.
	
	
	
	
	//These are generated by IDE to access private data in other classes.
	
	
	//This method is used to get name.
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getSalary() {
		return salary;
	}
	public void setSalary(int salary) {
		this.salary = salary;
	}

}
